# Generated by Django 3.2.16 on 2022-11-15 04:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kit',
            options={'ordering': ['name'], 'verbose_name': 'Kit', 'verbose_name_plural': 'Kits'},
        ),
        migrations.AlterField(
            model_name='kit',
            name='successful',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Ratio de exito'),
        ),
    ]
