# Generated by Django 3.2.16 on 2022-11-15 04:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreign_word', models.CharField(max_length=50, verbose_name='Palabra foranea')),
                ('native_word', models.CharField(max_length=50, verbose_name='Palabra nativa')),
                ('hits', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999)], verbose_name='Aciertos')),
                ('mistakes', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999)], verbose_name='Errores')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='kit.kit', verbose_name='Kit')),
            ],
        ),
    ]
