# Generated by Django 3.2.16 on 2022-12-03 09:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_auto_20221115_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='success',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Ratio de exito'),
        ),
    ]
