# Generated by Django 3.2.16 on 2022-11-17 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre de template')),
                ('view', models.CharField(max_length=50, verbose_name='Nombre de vista')),
            ],
            options={
                'verbose_name': 'Traducción de template',
                'verbose_name_plural': 'Traducciónes de templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ElementTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre de elemento')),
                ('selector', models.CharField(max_length=150, verbose_name='Selector CSS')),
                ('spanish_text', models.CharField(max_length=150, verbose_name='Texto en español')),
                ('english_text', models.CharField(max_length=150, verbose_name='Texto en inglés')),
                ('templatetranslation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementstranslation', to='templatetranslation.templatetranslation', verbose_name='Traducción de template')),
            ],
            options={
                'verbose_name': 'Traducción de elemento',
                'verbose_name_plural': 'Traducciónes de elementos',
                'ordering': ['name'],
            },
        ),
    ]
