# Generated by Django 3.2.16 on 2022-11-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templatetranslation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementtranslation',
            name='english_text',
            field=models.CharField(max_length=1500, verbose_name='Texto en inglés'),
        ),
        migrations.AlterField(
            model_name='elementtranslation',
            name='spanish_text',
            field=models.CharField(max_length=1500, verbose_name='Texto en español'),
        ),
    ]
