# Generated by Django 3.2.16 on 2022-11-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templatetranslation', '0003_auto_20221117_0426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementtranslation',
            name='templatetranslation',
        ),
        migrations.AddField(
            model_name='elementtranslation',
            name='templatetranslation',
            field=models.ManyToManyField(related_name='elementstranslation', to='templatetranslation.TemplateTranslation', verbose_name='Traducción de template'),
        ),
    ]
