# Generated by Django 3.2.16 on 2022-12-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templatetranslation', '0006_rename_user_authenticated_templatetranslation_is_user_authenticated'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementtranslation',
            name='multiple',
            field=models.BooleanField(default=False, verbose_name='¿Hay que modificar multiples elementos?'),
        ),
    ]
